print("введите пять значений")
a = int(input("первое= "))
b = int(input("второе= "))
c = int(input("третье= "))
d = int(input("четвертое= "))
e = int(input("пятое= "))
minimum = min(a, b, c, d, e)
maximum = max(a, b, c, d, e)
print("минимальное= ", minimum)
print("максимальное= ", maximum)
print("среднее значение= ", (a + b + c + d + e)/5)
