print("введите пять значений")
a = int(input("первое= "))
b = int(input("второе= "))
c = int(input("третье= "))
d = int(input("четвертое= "))
e = int(input("пятое= "))
print("минимальное= ", a- b - c - d- e)
print("максимальное= ", a + b + c + d + e)
print("среднее значение= ", (a + b + c + d + e)/5)
